# Generated by Django 4.2.7 on 2024-02-22 09:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_message_remove_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-sent_time'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='message',
            name='sent_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
