# Generated by Django 4.1.7 on 2024-03-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_messagereadstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver_is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='sender_is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='MessageReadStatus',
        ),
    ]
